### ISSUE TITLE
Considering updating going forward?

### ISSUE THREAD

**Issue by Strit** [Mostly-BSD/linux#1]
Hi @Linux-BSD .

I was just wondering if you have considered doing updates to the kernel going forward?
Like updating to 5.1, 5.2 etc ?

**Comment by Mostly-BSD** [comment]
https://github.com/anarsoul/linux-2.6 is already at 5.2. My fork was his 5.0 + bootlin's patches for 5.0 https://github.com/bootlin/linux-cedrus/tree/cedrus/5.0/next.
There are currently no patches there for 5.2. If they release any patches for 5.2, I'll rebase them on top of Anarsoul's 5.2 and commit here.

**Comment by Strit** [comment]
Okay cool.

I am using Anarsoul's branch until the LCD driver gets into mainline. :)

**Comment by Mostly-BSD** [comment]
I just opened a 5.2.11 branch. It's basically 5.2.11 + Anarsoul's patches on top. I don't have the time and patience to cherry pick from his commits or to maintain the same commit history, so I just did a git diff between his master and 5.2.7, and applied it on top of 5.2.11. It's working fine on my Pine64s.
